services:
  - type: web
    name: langflow
    runtime: docker
    dockerfilePath: ./Dockerfile  # oder ./docker/render.Dockerfile
    branch: main
    plan: standard  # mind. 2GB RAM nötig
    healthCheckPath: /health
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: sqlite:////app/data/.cache/langflow/langflow.db
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        value: "7860"
      - key: LANGFLOW_LOG_LEVEL
        value: INFO
    disk:
      name: langflow-data
      mountPath: /app/data
